### ISSUE TITLE
Release 4.0 final version

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.app.wsgi#1]
Are there any open issues preventing a 4.0 final release?

@mgedmin, @strichter, @kedder: You guys worked on the py3 branch where the 4.0.0aX releases seem to come from. Any objections to do it now?

- [x] Release final version of [zope.app.publication](https://github.com/zopefoundation/zope.app.publication/tree/py3)
- [x] Release final version of [zope.app.appsetup](https://github.com/zopefoundation/zope.app.appsetup/tree/py3) See [PR](https://github.com/zopefoundation/zope.app.appsetup/pull/2)
- [x] Add compatibility with Python 3.4 and 3.5

**Comment by icemac** [comment]
Added a to do list of my findings.

**Comment by mgedmin** [comment]
IIRC everything zope.* 4.0.0alpha that isn't released yet was blocked on zope.testbrowser, which introduced an incompatible API (no more magic thread-local, now you have to pass a WSGI app directly to the test layer or something like that) but didn't document how packages using it should adapt.

See https://github.com/zopefoundation/zope.testbrowser/issues/11

**Comment by icemac** [comment]
@mgedmin: At least `zope.app.wsgi` does not depend on `zope.testbrowser`. (I looked into the generated `bin/test` script. So it should not be blocked by  `zope.testbrowser`. 😀

**Comment by mgedmin** [comment]
Good thing I hedged my answer with that IIRC then ;)
